config/routes.rb
Rails.application.routes.draw do
  resources :depts

  resources :users

  resources :responses

  root to: redirect('/iquiries')
  
  resources :inquiries

end

app/models/dept.rb
class Dept < ActiveRecord::Base
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  belongs_to :user
  belongs_to :dept
  has_many :responses
end

app/models/login.rb
class Login < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :User
  belongs_to :Inquiry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :edit, :update, :destroy]

  # GET /depts
  # GET /depts.json
  def index
    @depts = Dept.all
  end

  # GET /depts/1
  # GET /depts/1.json
  def show
  end

  # GET /depts/new
  def new
    @dept = Dept.new
  end

  # GET /depts/1/edit
  def edit
  end

  # POST /depts
  # POST /depts.json
  def create
    @dept = Dept.new(dept_params)

    respond_to do |format|
      if @dept.save
        format.html { redirect_to @dept, notice: 'Dept was successfully created.' }
        format.json { render :show, status: :created, location: @dept }
      else
        format.html { render :new }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depts/1
  # PATCH/PUT /depts/1.json
  def update
    respond_to do |format|
      if @dept.update(dept_params)
        format.html { redirect_to @dept, notice: 'Dept was successfully updated.' }
        format.json { render :show, status: :ok, location: @dept }
      else
        format.html { render :edit }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depts/1
  # DELETE /depts/1.json
  def destroy
    @dept.destroy
    respond_to do |format|
      format.html { redirect_to depts_url, notice: 'Dept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dept
      @dept = Dept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dept_params
      params.require(:dept).permit(:code, :name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:accepted_datetime, :user_id, :inquired_person, :dept_id, :contents)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to @response, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:responsed_detetime, :user_id, :contents, :inquiry_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/depts/_form.html.erb
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depts/edit.html.erb
<h1>Editing dept</h1>

<%= render 'form' %>

<%= link_to 'Show', @dept %> |
<%= link_to 'Back', depts_path %>

app/views/depts/index.html.erb
<h1>Listing depts</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @depts.each do |dept| %>
      <tr>
        <td><%= dept.code %></td>
        <td><%= dept.name %></td>
        <td><%= link_to 'Show', dept %></td>
        <td><%= link_to 'Edit', edit_dept_path(dept) %></td>
        <td><%= link_to 'Destroy', dept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dept', new_dept_path %>

app/views/depts/new.html.erb
<h1>New dept</h1>

<%= render 'form' %>

<%= link_to 'Back', depts_path %>

app/views/depts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @dept.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dept.name %>
</p>

<%= link_to 'Edit', edit_dept_path(@dept) %> |
<%= link_to 'Back', depts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :accepted_datetime %><br>
    <%= f.datetime_select :accepted_datetime %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :inquired_person %><br>
    <%= f.text_field :inquired_person %>
  </div>
  <div class="field">
    <%= f.label :dept_id %><br>
    <%= f.number_field :dept_id %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing inquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<h1>Listing inquiries</h1>

<table>
  <thead>
    <tr>
      <th>Accepted datetime</th>
      <th>User1</th>
      <th>Inquired person</th>
      <th>Dept</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.accepted_datetime %></td>
        <td><%= inquiry.user_id %></td>
        <td><%= inquiry.inquired_person %></td>
        <td><%= inquiry.dept_id %></td>
        <td><%= inquiry.contents %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<h1>New inquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accepted datetime:</strong>
  <%= @inquiry.accepted_datetime %>
</p>

<p>
  <strong>User:</strong>
  <%= @inquiry.user.name %>
</p>

<p>
  <strong>Inquired person:</strong>
  <%= @inquiry.inquired_person %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @inquiry.dept.name %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @inquiry.contents %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelpdeskMgt2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p clss="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= t('view.responsed_detetime') %><br>
    <%= f.datetime_select :responsed_detetime %>
  </div>
  <div class="field">
    <%= f.label :User_id %><br>
    <%= f.text_field :User_id %>
  </div>
  <div class="field">
    <%= t('view.contents') %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="field">
    <%= f.label :inquiry_id %><br>
    <%= f.number_field :inquiry_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<hr>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <thead>
    <tr>
      <th>Responsed detetime</th>
      <th>User</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.responsed_detetime %></td>
        <td><%= response.User %></td>
        <td><%= response.contents %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Responsed detetime:</strong>
  <%= t('view.responsed_detetime') %>
</p>

<p>
  <strong>User:</strong>
  <%= @response.User %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @response.contents %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>